### ISSUE TITLE
OCC commands doesn't work

### ISSUE THREAD

**Issue by sebastiencastermans** [eldertek/duplicatefinder#9]
Hi,

I have my nextcloud server in a docker with Nextcloud All-In-One. 
For OCC command, I run this command in my local terminal : `sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ`. All other commands run correctly but with the latest version of duplicate finder, I cannot run any command.

I run this command : 
`sudo docker exec --user www-data -it nextcloud-aio-nextcloud php occ duplicates:find-all -u admin`
 and the response with errors is that : 
```
An unhandled exception has been thrown:
Error: Interface "OCA\Files_Versions\Versions\INeedSyncVersionBackend" not found in /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php:46
Stack trace:
#0 /var/www/html/lib/composer/composer/ClassLoader.php(582): include()
#1 /var/www/html/lib/composer/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/var/www/html/c...')
#2 /var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php(138): Composer\Autoload\ClassLoader->loadClass('OCA\\GroupFolder...')
#3 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#4 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#5 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#6 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#7 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#8 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(97): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...', true)
#9 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(ReflectionParameter))
#10 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(116): array_map(Object(Closure), Array)
#11 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
#12 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(142): OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\GroupFolder...')
#13 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(494): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#14 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(466): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#15 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(65): OC\AppFramework\DependencyInjection\DIContainer->query('OCA\\GroupFolder...')
#16 /var/www/html/custom_apps/groupfolders/lib/AppInfo/Application.php(158): OC\AppFramework\Utility\SimpleContainer->get('OCA\\GroupFolder...')
#17 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OCA\GroupFolders\AppInfo\Application->OCA\GroupFolders\AppInfo\{closure}(Object(OC\AppFramework\DependencyInjection\DIContainer))
#18 /var/www/html/3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(Pimple\Container))
#19 /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php(138): Pimple\Container->offsetGet('OCA\\GroupFolder...')
#20 /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php(488): OC\AppFramework\Utility\SimpleContainer->query('OCA\\GroupFolder...')
#21 /var/www/html/lib/private/ServerContainer.php(155): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback('OCA\\GroupFolder...')
#22 /var/www/html/lib/private/Console/Application.php(217): OC\ServerContainer->query('OCA\\GroupFolder...')
#23 /var/www/html/lib/private/Console/Application.php(131): OC\Console\Application->loadCommandsFromInfoXml(Array)
#24 /var/www/html/console.php(99): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/occ(11): require_once('/var/www/html/c...')
#26 {main}
```

**Comment by eldertek** [comment]
Not a duplicate finder issue, please refer to groupfolders

**Comment by sebastiencastermans** [comment]
You are right! I'm sorry, I didn't correctly check before posting this issue. Sorry. Have a good day and... Thanks for the update 🙃!

**Comment by eldertek** [comment]
> You are right! I'm sorry, I didn't correctly check before posting this issue. Sorry. Have a good day and... Thanks for the update 🙃!

Your welcome =)

**Comment by ilsawa** [comment]
I have a clean (not docker) nextcloud installation and I carefully make sure that it is updated to the latest stable version.
I haven't seen a solution to the problem here, but I'm writing here because it seems to me it's also related to groupfolders:

sudo -u www-data php /var/www/nextcloud/occ duplicates:find-all -u sawa
Start searching files for sawa in path /sawa/files

In Common.php line 767:
                                                                                                                      
  "files/1814873ac5c3b95f669143535d5d57ae"("__groupfolders/1/scanner::") is locked, existing lock on file: exclusive  
                                                                                                                      

In MemcacheLockingProvider.php line 67:
                                                                                                                                                       
  "files/1814873ac5c3b95f669143535d5d57ae"("local::/var/www/nextcloud/data/::__groupfolders/1/scanner::") is locked, existing lock on file: exclusive  
                                                                                                                                                       
Can someone explain to me what I have to do to make it work?

**Comment by eldertek** [comment]
Please clear your redis cache if you use it or cache related, try to delete lock on these folders too by db
